// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/chapter_paragraphs.proto" (syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { StringValue } from "../google/protobuf/wrappers";
/**
 * @generated from protobuf message GetChapterParagraphRequest
 */
export interface GetChapterParagraphRequest {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
}
/**
 * @generated from protobuf message GetChapterParagraphResponse
 */
export interface GetChapterParagraphResponse {
    /**
     * @generated from protobuf field: ChapterParagraph item = 1;
     */
    item?: ChapterParagraph;
}
/**
 * @generated from protobuf message ChapterParagraph
 */
export interface ChapterParagraph {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: int32 chapterId = 2;
     */
    chapterId: number;
    /**
     * @generated from protobuf field: int32 totalComments = 3;
     */
    totalComments: number;
    /**
     * @generated from protobuf field: google.protobuf.StringValue content = 4;
     */
    content?: StringValue;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetChapterParagraphRequest$Type extends MessageType<GetChapterParagraphRequest> {
    constructor() {
        super("GetChapterParagraphRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message GetChapterParagraphRequest
 */
export const GetChapterParagraphRequest = new GetChapterParagraphRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetChapterParagraphResponse$Type extends MessageType<GetChapterParagraphResponse> {
    constructor() {
        super("GetChapterParagraphResponse", [
            { no: 1, name: "item", kind: "message", T: () => ChapterParagraph }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message GetChapterParagraphResponse
 */
export const GetChapterParagraphResponse = new GetChapterParagraphResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ChapterParagraph$Type extends MessageType<ChapterParagraph> {
    constructor() {
        super("ChapterParagraph", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "chapterId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "totalComments", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "content", kind: "message", T: () => StringValue }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ChapterParagraph
 */
export const ChapterParagraph = new ChapterParagraph$Type();
/**
 * @generated ServiceType for protobuf service ChapterParagraphs
 */
export const ChapterParagraphs = new ServiceType("ChapterParagraphs", [
    { name: "GetChapterParagraph", options: {}, I: GetChapterParagraphRequest, O: GetChapterParagraphResponse }
]);
