// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/missions.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Missions } from "./missions";
import type { CompleteMissionResponse } from "./missions";
import type { CompleteMissionRequest } from "./missions";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetMyCompletedMissionsResponse } from "./missions";
import type { GetMyCompletedMissionsRequest } from "./missions";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service wuxiaworld.api.v2.Missions
 */
export interface IMissionsClient {
    /**
     * @generated from protobuf rpc: GetMyCompletedMissions(wuxiaworld.api.v2.GetMyCompletedMissionsRequest) returns (wuxiaworld.api.v2.GetMyCompletedMissionsResponse);
     */
    getMyCompletedMissions(input: GetMyCompletedMissionsRequest, options?: RpcOptions): UnaryCall<GetMyCompletedMissionsRequest, GetMyCompletedMissionsResponse>;
    /**
     * @generated from protobuf rpc: CompleteMission(wuxiaworld.api.v2.CompleteMissionRequest) returns (wuxiaworld.api.v2.CompleteMissionResponse);
     */
    completeMission(input: CompleteMissionRequest, options?: RpcOptions): UnaryCall<CompleteMissionRequest, CompleteMissionResponse>;
}
/**
 * @generated from protobuf service wuxiaworld.api.v2.Missions
 */
export class MissionsClient implements IMissionsClient, ServiceInfo {
    typeName = Missions.typeName;
    methods = Missions.methods;
    options = Missions.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetMyCompletedMissions(wuxiaworld.api.v2.GetMyCompletedMissionsRequest) returns (wuxiaworld.api.v2.GetMyCompletedMissionsResponse);
     */
    getMyCompletedMissions(input: GetMyCompletedMissionsRequest, options?: RpcOptions): UnaryCall<GetMyCompletedMissionsRequest, GetMyCompletedMissionsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMyCompletedMissionsRequest, GetMyCompletedMissionsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CompleteMission(wuxiaworld.api.v2.CompleteMissionRequest) returns (wuxiaworld.api.v2.CompleteMissionResponse);
     */
    completeMission(input: CompleteMissionRequest, options?: RpcOptions): UnaryCall<CompleteMissionRequest, CompleteMissionResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CompleteMissionRequest, CompleteMissionResponse>("unary", this._transport, method, opt, input);
    }
}
