// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/missions.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { KarmaTransactionItem } from "./karma";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetMyCompletedMissionsRequest
 */
export interface GetMyCompletedMissionsRequest {
    /**
     * @generated from protobuf oneof: timeCompleted
     */
    timeCompleted: {
        oneofKind: "today";
        /**
         * @generated from protobuf field: bool today = 1;
         */
        today: boolean;
    } | {
        oneofKind: "date";
        /**
         * @generated from protobuf field: google.protobuf.Timestamp date = 2;
         */
        date: Timestamp;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetMyCompletedMissionsResponse
 */
export interface GetMyCompletedMissionsResponse {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.MissionItem items = 1;
     */
    items: MissionItem[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.CompleteMissionRequest
 */
export interface CompleteMissionRequest {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionItem.MissionType missionType = 1;
     */
    missionType: MissionItem_MissionType;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionItem.RewardType rewardType = 2;
     */
    rewardType: MissionItem_RewardType;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.CompleteMissionResponse
 */
export interface CompleteMissionResponse {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionItem item = 1;
     */
    item?: MissionItem;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.MissionItem
 */
export interface MissionItem {
    /**
     * @generated from protobuf field: bool completed = 1;
     */
    completed: boolean;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp completedAt = 2;
     */
    completedAt?: Timestamp;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionItem.MissionType missionType = 3;
     */
    missionType: MissionItem_MissionType;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionItem.RewardType rewardType = 4;
     */
    rewardType: MissionItem_RewardType;
    /**
     * @generated from protobuf oneof: rewardItem
     */
    rewardItem: {
        oneofKind: "karma";
        /**
         * @generated from protobuf field: wuxiaworld.api.v2.KarmaTransactionItem karma = 5;
         */
        karma: KarmaTransactionItem;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.MissionItem.MissionType
 */
export enum MissionItem_MissionType {
    /**
     * @generated from protobuf enum value: MissionTypeNone = 0;
     */
    MissionTypeNone = 0,
    /**
     * @generated from protobuf enum value: MissionTypeCheckIn = 1;
     */
    MissionTypeCheckIn = 1,
    /**
     * @generated from protobuf enum value: MissionTypeComment = 2;
     */
    MissionTypeComment = 2
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.MissionItem.RewardType
 */
export enum MissionItem_RewardType {
    /**
     * @generated from protobuf enum value: RewardTypeNone = 0;
     */
    RewardTypeNone = 0,
    /**
     * @generated from protobuf enum value: RewardTypeKarma = 1;
     */
    RewardTypeKarma = 1
}
// @generated message type with reflection information, may provide speed optimized methods
class GetMyCompletedMissionsRequest$Type extends MessageType<GetMyCompletedMissionsRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetMyCompletedMissionsRequest", [
            { no: 1, name: "today", kind: "scalar", oneof: "timeCompleted", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "date", kind: "message", oneof: "timeCompleted", T: () => Timestamp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetMyCompletedMissionsRequest
 */
export const GetMyCompletedMissionsRequest = new GetMyCompletedMissionsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMyCompletedMissionsResponse$Type extends MessageType<GetMyCompletedMissionsResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetMyCompletedMissionsResponse", [
            { no: 1, name: "items", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MissionItem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetMyCompletedMissionsResponse
 */
export const GetMyCompletedMissionsResponse = new GetMyCompletedMissionsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CompleteMissionRequest$Type extends MessageType<CompleteMissionRequest> {
    constructor() {
        super("wuxiaworld.api.v2.CompleteMissionRequest", [
            { no: 1, name: "missionType", kind: "enum", T: () => ["wuxiaworld.api.v2.MissionItem.MissionType", MissionItem_MissionType] },
            { no: 2, name: "rewardType", kind: "enum", T: () => ["wuxiaworld.api.v2.MissionItem.RewardType", MissionItem_RewardType] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.CompleteMissionRequest
 */
export const CompleteMissionRequest = new CompleteMissionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CompleteMissionResponse$Type extends MessageType<CompleteMissionResponse> {
    constructor() {
        super("wuxiaworld.api.v2.CompleteMissionResponse", [
            { no: 1, name: "item", kind: "message", T: () => MissionItem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.CompleteMissionResponse
 */
export const CompleteMissionResponse = new CompleteMissionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MissionItem$Type extends MessageType<MissionItem> {
    constructor() {
        super("wuxiaworld.api.v2.MissionItem", [
            { no: 1, name: "completed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "completedAt", kind: "message", T: () => Timestamp },
            { no: 3, name: "missionType", kind: "enum", T: () => ["wuxiaworld.api.v2.MissionItem.MissionType", MissionItem_MissionType] },
            { no: 4, name: "rewardType", kind: "enum", T: () => ["wuxiaworld.api.v2.MissionItem.RewardType", MissionItem_RewardType] },
            { no: 5, name: "karma", kind: "message", oneof: "rewardItem", T: () => KarmaTransactionItem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.MissionItem
 */
export const MissionItem = new MissionItem$Type();
/**
 * @generated ServiceType for protobuf service wuxiaworld.api.v2.Missions
 */
export const Missions = new ServiceType("wuxiaworld.api.v2.Missions", [
    { name: "GetMyCompletedMissions", options: {}, I: GetMyCompletedMissionsRequest, O: GetMyCompletedMissionsResponse },
    { name: "CompleteMission", options: {}, I: CompleteMissionRequest, O: CompleteMissionResponse }
]);
