// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/novel_announcements.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { Int32Value } from "../google/protobuf/wrappers";
import { NovelInfo } from "./novels";
import { UserItem } from "./users";
import { Timestamp } from "../google/protobuf/timestamp";
import { PageInfoResponse } from "./pagination";
import { BoolValue } from "../google/protobuf/wrappers";
import { PageInfoRequest } from "./pagination";
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetNovelAnnouncementRequest
 */
export interface GetNovelAnnouncementRequest {
    /**
     * @generated from protobuf oneof: byProperty
     */
    byProperty: {
        oneofKind: "id";
        /**
         * @generated from protobuf field: int32 id = 1;
         */
        id: number;
    } | {
        oneofKind: "slug";
        /**
         * @generated from protobuf field: wuxiaworld.api.v2.GetNovelAnnouncementRequest.BySlug slug = 2;
         */
        slug: GetNovelAnnouncementRequest_BySlug;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetNovelAnnouncementRequest.BySlug
 */
export interface GetNovelAnnouncementRequest_BySlug {
    /**
     * @generated from protobuf field: string slug = 1;
     */
    slug: string;
    /**
     * @generated from protobuf oneof: novelSelector
     */
    novelSelector: {
        oneofKind: "novelId";
        /**
         * @generated from protobuf field: int32 novelId = 2;
         */
        novelId: number;
    } | {
        oneofKind: "novelSlug";
        /**
         * @generated from protobuf field: string novelSlug = 3;
         */
        novelSlug: string;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetNovelAnnouncementResponse
 */
export interface GetNovelAnnouncementResponse {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.NovelAnnouncementItem item = 1;
     */
    item?: NovelAnnouncementItem;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetNovelAnnouncementsRequest
 */
export interface GetNovelAnnouncementsRequest {
    /**
     * @generated from protobuf oneof: novelSelector
     */
    novelSelector: {
        oneofKind: "novelId";
        /**
         * @generated from protobuf field: int32 novelId = 1;
         */
        novelId: number;
    } | {
        oneofKind: "novelSlug";
        /**
         * @generated from protobuf field: string novelSlug = 2;
         */
        novelSlug: string;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PageInfoRequest pageInfo = 3;
     */
    pageInfo?: PageInfoRequest;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.GetNovelAnnouncementsRequest.Filter filter = 4;
     */
    filter?: GetNovelAnnouncementsRequest_Filter;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetNovelAnnouncementsRequest.Filter
 */
export interface GetNovelAnnouncementsRequest_Filter {
    /**
     * @generated from protobuf field: google.protobuf.BoolValue isSponsorsOnly = 1;
     */
    isSponsorsOnly?: BoolValue;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetNovelAnnouncementsResponse
 */
export interface GetNovelAnnouncementsResponse {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.NovelAnnouncementItem items = 1;
     */
    items: NovelAnnouncementItem[];
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PageInfoResponse pageInfo = 2;
     */
    pageInfo?: PageInfoResponse;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.NovelAnnouncementItem
 */
export interface NovelAnnouncementItem {
    /**
     * @generated from protobuf field: int32 entityId = 1;
     */
    entityId: number;
    /**
     * @generated from protobuf field: string slug = 2;
     */
    slug: string;
    /**
     * @generated from protobuf field: string content = 3;
     */
    content: string;
    /**
     * @generated from protobuf field: bool isSticky = 4;
     */
    isSticky: boolean;
    /**
     * @generated from protobuf field: string title = 5;
     */
    title: string;
    /**
     * @generated from protobuf field: bool isSponsorsOnly = 6;
     */
    isSponsorsOnly: boolean;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp whenToPublish = 7;
     */
    whenToPublish?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp timePublished = 8;
     */
    timePublished?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp lastModified = 9;
     */
    lastModified?: Timestamp;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.UserItem poster = 10;
     */
    poster?: UserItem;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.NovelInfo novelInfo = 11;
     */
    novelInfo?: NovelInfo;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value totalComments = 12;
     */
    totalComments?: Int32Value;
    /**
     * @generated from protobuf field: bool allowComments = 13;
     */
    allowComments: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetNovelAnnouncementRequest$Type extends MessageType<GetNovelAnnouncementRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetNovelAnnouncementRequest", [
            { no: 1, name: "id", kind: "scalar", oneof: "byProperty", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "slug", kind: "message", oneof: "byProperty", T: () => GetNovelAnnouncementRequest_BySlug }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetNovelAnnouncementRequest
 */
export const GetNovelAnnouncementRequest = new GetNovelAnnouncementRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetNovelAnnouncementRequest_BySlug$Type extends MessageType<GetNovelAnnouncementRequest_BySlug> {
    constructor() {
        super("wuxiaworld.api.v2.GetNovelAnnouncementRequest.BySlug", [
            { no: 1, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "novelId", kind: "scalar", oneof: "novelSelector", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "novelSlug", kind: "scalar", oneof: "novelSelector", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetNovelAnnouncementRequest.BySlug
 */
export const GetNovelAnnouncementRequest_BySlug = new GetNovelAnnouncementRequest_BySlug$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetNovelAnnouncementResponse$Type extends MessageType<GetNovelAnnouncementResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetNovelAnnouncementResponse", [
            { no: 1, name: "item", kind: "message", T: () => NovelAnnouncementItem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetNovelAnnouncementResponse
 */
export const GetNovelAnnouncementResponse = new GetNovelAnnouncementResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetNovelAnnouncementsRequest$Type extends MessageType<GetNovelAnnouncementsRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetNovelAnnouncementsRequest", [
            { no: 1, name: "novelId", kind: "scalar", oneof: "novelSelector", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "novelSlug", kind: "scalar", oneof: "novelSelector", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "pageInfo", kind: "message", T: () => PageInfoRequest, options: { "wuxiaworld.api.v2.required": { value: true } } },
            { no: 4, name: "filter", kind: "message", T: () => GetNovelAnnouncementsRequest_Filter }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetNovelAnnouncementsRequest
 */
export const GetNovelAnnouncementsRequest = new GetNovelAnnouncementsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetNovelAnnouncementsRequest_Filter$Type extends MessageType<GetNovelAnnouncementsRequest_Filter> {
    constructor() {
        super("wuxiaworld.api.v2.GetNovelAnnouncementsRequest.Filter", [
            { no: 1, name: "isSponsorsOnly", kind: "message", T: () => BoolValue }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetNovelAnnouncementsRequest.Filter
 */
export const GetNovelAnnouncementsRequest_Filter = new GetNovelAnnouncementsRequest_Filter$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetNovelAnnouncementsResponse$Type extends MessageType<GetNovelAnnouncementsResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetNovelAnnouncementsResponse", [
            { no: 1, name: "items", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => NovelAnnouncementItem },
            { no: 2, name: "pageInfo", kind: "message", T: () => PageInfoResponse }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetNovelAnnouncementsResponse
 */
export const GetNovelAnnouncementsResponse = new GetNovelAnnouncementsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NovelAnnouncementItem$Type extends MessageType<NovelAnnouncementItem> {
    constructor() {
        super("wuxiaworld.api.v2.NovelAnnouncementItem", [
            { no: 1, name: "entityId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "isSticky", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "isSponsorsOnly", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "whenToPublish", kind: "message", T: () => Timestamp },
            { no: 8, name: "timePublished", kind: "message", T: () => Timestamp },
            { no: 9, name: "lastModified", kind: "message", T: () => Timestamp },
            { no: 10, name: "poster", kind: "message", T: () => UserItem },
            { no: 11, name: "novelInfo", kind: "message", T: () => NovelInfo },
            { no: 12, name: "totalComments", kind: "message", T: () => Int32Value },
            { no: 13, name: "allowComments", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.NovelAnnouncementItem
 */
export const NovelAnnouncementItem = new NovelAnnouncementItem$Type();
/**
 * @generated ServiceType for protobuf service wuxiaworld.api.v2.NovelAnnouncements
 */
export const NovelAnnouncements = new ServiceType("wuxiaworld.api.v2.NovelAnnouncements", [
    { name: "GetNovelAnnouncement", options: {}, I: GetNovelAnnouncementRequest, O: GetNovelAnnouncementResponse },
    { name: "GetNovelAnnouncements", options: {}, I: GetNovelAnnouncementsRequest, O: GetNovelAnnouncementsResponse }
]);
