// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/reviews.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { UserItem } from "./users";
import { Timestamp } from "../google/protobuf/timestamp";
import { StringValue } from "../google/protobuf/wrappers";
import { PageInfoResponse } from "./pagination";
import { PageInfoRequest } from "./pagination";
/**
 * @generated from protobuf message wuxiaworld.api.v2.CreateReviewRequest
 */
export interface CreateReviewRequest {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ReviewItem.VoteType voteType = 1;
     */
    voteType: ReviewItem_VoteType;
    /**
     * @generated from protobuf field: string content = 2;
     */
    content: string;
    /**
     * @generated from protobuf oneof: type
     */
    type: {
        oneofKind: "novelId";
        /**
         * @generated from protobuf field: int32 novelId = 3;
         */
        novelId: number;
    } | {
        oneofKind: "productId";
        /**
         * @generated from protobuf field: int32 productId = 4;
         */
        productId: number;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.CreateReviewResponse
 */
export interface CreateReviewResponse {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ReviewItem item = 1;
     */
    item?: ReviewItem;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.UpdateReviewRequest
 */
export interface UpdateReviewRequest {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ReviewItem.VoteType voteType = 2;
     */
    voteType: ReviewItem_VoteType;
    /**
     * @generated from protobuf field: string content = 3;
     */
    content: string;
    /**
     * @generated from protobuf oneof: type
     */
    type: {
        oneofKind: "novelId";
        /**
         * @generated from protobuf field: int32 novelId = 4;
         */
        novelId: number;
    } | {
        oneofKind: "productId";
        /**
         * @generated from protobuf field: int32 productId = 5;
         */
        productId: number;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.UpdateReviewResponse
 */
export interface UpdateReviewResponse {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ReviewItem item = 1;
     */
    item?: ReviewItem;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.SubmitReviewVoteRequest
 */
export interface SubmitReviewVoteRequest {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ReviewType type = 2;
     */
    type: ReviewType;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ReviewItem.VoteType voteType = 3;
     */
    voteType: ReviewItem_VoteType;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.SubmitReviewVoteResponse
 */
export interface SubmitReviewVoteResponse {
    /**
     * @generated from protobuf field: bool result = 1;
     */
    result: boolean;
    /**
     * @generated from protobuf field: int32 upVotes = 2;
     */
    upVotes: number;
    /**
     * @generated from protobuf field: int32 downVotes = 3;
     */
    downVotes: number;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetUserReviewRequest
 */
export interface GetUserReviewRequest {
    /**
     * @generated from protobuf field: string userId = 1;
     */
    userId: string;
    /**
     * @generated from protobuf oneof: type
     */
    type: {
        oneofKind: "novelId";
        /**
         * @generated from protobuf field: int32 novelId = 2;
         */
        novelId: number;
    } | {
        oneofKind: "productId";
        /**
         * @generated from protobuf field: int32 productId = 3;
         */
        productId: number;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetUserReviewResponse
 */
export interface GetUserReviewResponse {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ReviewItem item = 1;
     */
    item?: ReviewItem;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetUserReviewsRequest
 */
export interface GetUserReviewsRequest {
    /**
     * @generated from protobuf field: string userId = 1;
     */
    userId: string;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.GetUserReviewsRequest.Type type = 2;
     */
    type: GetUserReviewsRequest_Type;
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.GetUserReviewsRequest.Type
 */
export enum GetUserReviewsRequest_Type {
    /**
     * @generated from protobuf enum value: All = 0;
     */
    All = 0,
    /**
     * @generated from protobuf enum value: Novels = 1;
     */
    Novels = 1,
    /**
     * @generated from protobuf enum value: Products = 2;
     */
    Products = 2
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetUserReviewsResponse
 */
export interface GetUserReviewsResponse {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.ReviewItem items = 1;
     */
    items: ReviewItem[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.SearchReviewsRequest
 */
export interface SearchReviewsRequest {
    /**
     * @generated from protobuf oneof: type
     */
    type: {
        oneofKind: "novelId";
        /**
         * @generated from protobuf field: int32 novelId = 1;
         */
        novelId: number;
    } | {
        oneofKind: "productId";
        /**
         * @generated from protobuf field: int32 productId = 2;
         */
        productId: number;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.SearchReviewsRequest.SortType sortType = 3;
     */
    sortType: SearchReviewsRequest_SortType;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ReviewItem.VoteType voteType = 5;
     */
    voteType: ReviewItem_VoteType;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PageInfoRequest pageInfo = 4;
     */
    pageInfo?: PageInfoRequest;
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.SearchReviewsRequest.SortType
 */
export enum SearchReviewsRequest_SortType {
    /**
     * @generated from protobuf enum value: Default = 0;
     */
    Default = 0,
    /**
     * @generated from protobuf enum value: Relevance = 1;
     */
    Relevance = 1,
    /**
     * @generated from protobuf enum value: Newest = 2;
     */
    Newest = 2,
    /**
     * @generated from protobuf enum value: Oldest = 3;
     */
    Oldest = 3,
    /**
     * @generated from protobuf enum value: Best = 4;
     */
    Best = 4,
    /**
     * @generated from protobuf enum value: Worst = 5;
     */
    Worst = 5
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.SearchReviewsResponse
 */
export interface SearchReviewsResponse {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.ReviewItem items = 1;
     */
    items: ReviewItem[];
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PageInfoResponse pageInfo = 2;
     */
    pageInfo?: PageInfoResponse;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.ReviewerSeriesInfo
 */
export interface ReviewerSeriesInfo {
    /**
     * @generated from protobuf field: bool isChampion = 1;
     */
    isChampion: boolean;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.ReviewerEntityInfo
 */
export interface ReviewerEntityInfo {
    /**
     * @generated from protobuf oneof: entityInfo
     */
    entityInfo: {
        oneofKind: "seriesInfo";
        /**
         * @generated from protobuf field: wuxiaworld.api.v2.ReviewerSeriesInfo seriesInfo = 1;
         */
        seriesInfo: ReviewerSeriesInfo;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.ReviewItem
 */
export interface ReviewItem {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: google.protobuf.StringValue content = 2;
     */
    content?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp reviewedAt = 3;
     */
    reviewedAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp editedAt = 4;
     */
    editedAt?: Timestamp;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.UserItem reviewUser = 5;
     */
    reviewUser?: UserItem;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ReviewItem.PastUser reviewUserPast = 6;
     */
    reviewUserPast?: ReviewItem_PastUser;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ReviewItem.Votes votes = 7;
     */
    votes?: ReviewItem_Votes;
    /**
     * @generated from protobuf field: int32 totalComments = 8;
     */
    totalComments: number;
    /**
     * @generated from protobuf oneof: type
     */
    type: {
        oneofKind: "novelId";
        /**
         * @generated from protobuf field: int32 novelId = 9;
         */
        novelId: number;
    } | {
        oneofKind: "productId";
        /**
         * @generated from protobuf field: int32 productId = 10;
         */
        productId: number;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ReviewItem.VoteType voteType = 11;
     */
    voteType: ReviewItem_VoteType;
    /**
     * @generated from protobuf field: bool hasPurchased = 12;
     */
    hasPurchased: boolean;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ReviewItem.RejectionInfo rejectionInfo = 13;
     */
    rejectionInfo?: ReviewItem_RejectionInfo;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ReviewerEntityInfo reviewerEntityInfo = 14;
     */
    reviewerEntityInfo?: ReviewerEntityInfo;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.ReviewItem.Votes
 */
export interface ReviewItem_Votes {
    /**
     * @generated from protobuf field: int32 upVotes = 1;
     */
    upVotes: number;
    /**
     * @generated from protobuf field: int32 downVotes = 2;
     */
    downVotes: number;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.ReviewItem.RejectionInfo
 */
export interface ReviewItem_RejectionInfo {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ReviewItem.RejectionInfo.State state = 1;
     */
    state: ReviewItem_RejectionInfo_State;
    /**
     * @generated from protobuf field: google.protobuf.StringValue reason = 2;
     */
    reason?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp rejectedAt = 3;
     */
    rejectedAt?: Timestamp;
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.ReviewItem.RejectionInfo.State
 */
export enum ReviewItem_RejectionInfo_State {
    /**
     * @generated from protobuf enum value: Default = 0;
     */
    Default = 0,
    /**
     * @generated from protobuf enum value: Rejected = 1;
     */
    Rejected = 1,
    /**
     * @generated from protobuf enum value: ReApproval = 2;
     */
    ReApproval = 2,
    /**
     * @generated from protobuf enum value: Approved = 3;
     */
    Approved = 3
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.ReviewItem.PastUser
 */
export interface ReviewItem_PastUser {
    /**
     * @generated from protobuf field: bool isVip = 1;
     */
    isVip: boolean;
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.ReviewItem.VoteType
 */
export enum ReviewItem_VoteType {
    /**
     * @generated from protobuf enum value: None = 0;
     */
    None = 0,
    /**
     * @generated from protobuf enum value: ThumbsDown = -1;
     */
    ThumbsDown = -1,
    /**
     * @generated from protobuf enum value: ThumbsUp = 1;
     */
    ThumbsUp = 1
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.ReviewType
 */
export enum ReviewType {
    /**
     * @generated from protobuf enum value: NoneReviewType = 0;
     */
    NoneReviewType = 0,
    /**
     * @generated from protobuf enum value: NovelReviewType = 1;
     */
    NovelReviewType = 1,
    /**
     * @generated from protobuf enum value: ProductReviewType = 2;
     */
    ProductReviewType = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateReviewRequest$Type extends MessageType<CreateReviewRequest> {
    constructor() {
        super("wuxiaworld.api.v2.CreateReviewRequest", [
            { no: 1, name: "voteType", kind: "enum", T: () => ["wuxiaworld.api.v2.ReviewItem.VoteType", ReviewItem_VoteType], options: { "wuxiaworld.api.v2.required": { value: true }, "wuxiaworld.api.v2.display": { name: "Vote Type" } } },
            { no: 2, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "wuxiaworld.api.v2.stringLength": { maxLength: { value: 8192 } }, "wuxiaworld.api.v2.display": { name: "Content" }, "wuxiaworld.api.v2.wordLength": { minWords: { value: 100 } } } },
            { no: 3, name: "novelId", kind: "scalar", oneof: "type", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "productId", kind: "scalar", oneof: "type", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.CreateReviewRequest
 */
export const CreateReviewRequest = new CreateReviewRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateReviewResponse$Type extends MessageType<CreateReviewResponse> {
    constructor() {
        super("wuxiaworld.api.v2.CreateReviewResponse", [
            { no: 1, name: "item", kind: "message", T: () => ReviewItem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.CreateReviewResponse
 */
export const CreateReviewResponse = new CreateReviewResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateReviewRequest$Type extends MessageType<UpdateReviewRequest> {
    constructor() {
        super("wuxiaworld.api.v2.UpdateReviewRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "voteType", kind: "enum", T: () => ["wuxiaworld.api.v2.ReviewItem.VoteType", ReviewItem_VoteType], options: { "wuxiaworld.api.v2.required": { value: true }, "wuxiaworld.api.v2.display": { name: "Vote Type" } } },
            { no: 3, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "wuxiaworld.api.v2.stringLength": { maxLength: { value: 8192 } }, "wuxiaworld.api.v2.display": { name: "Content" }, "wuxiaworld.api.v2.wordLength": { minWords: { value: 100 } } } },
            { no: 4, name: "novelId", kind: "scalar", oneof: "type", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "productId", kind: "scalar", oneof: "type", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.UpdateReviewRequest
 */
export const UpdateReviewRequest = new UpdateReviewRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateReviewResponse$Type extends MessageType<UpdateReviewResponse> {
    constructor() {
        super("wuxiaworld.api.v2.UpdateReviewResponse", [
            { no: 1, name: "item", kind: "message", T: () => ReviewItem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.UpdateReviewResponse
 */
export const UpdateReviewResponse = new UpdateReviewResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubmitReviewVoteRequest$Type extends MessageType<SubmitReviewVoteRequest> {
    constructor() {
        super("wuxiaworld.api.v2.SubmitReviewVoteRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["wuxiaworld.api.v2.ReviewType", ReviewType] },
            { no: 3, name: "voteType", kind: "enum", T: () => ["wuxiaworld.api.v2.ReviewItem.VoteType", ReviewItem_VoteType], options: { "wuxiaworld.api.v2.required": { value: true }, "wuxiaworld.api.v2.display": { name: "Vote Type" } } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.SubmitReviewVoteRequest
 */
export const SubmitReviewVoteRequest = new SubmitReviewVoteRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubmitReviewVoteResponse$Type extends MessageType<SubmitReviewVoteResponse> {
    constructor() {
        super("wuxiaworld.api.v2.SubmitReviewVoteResponse", [
            { no: 1, name: "result", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "upVotes", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "downVotes", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.SubmitReviewVoteResponse
 */
export const SubmitReviewVoteResponse = new SubmitReviewVoteResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserReviewRequest$Type extends MessageType<GetUserReviewRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetUserReviewRequest", [
            { no: 1, name: "userId", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "wuxiaworld.api.v2.required": { value: true } } },
            { no: 2, name: "novelId", kind: "scalar", oneof: "type", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "productId", kind: "scalar", oneof: "type", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetUserReviewRequest
 */
export const GetUserReviewRequest = new GetUserReviewRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserReviewResponse$Type extends MessageType<GetUserReviewResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetUserReviewResponse", [
            { no: 1, name: "item", kind: "message", T: () => ReviewItem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetUserReviewResponse
 */
export const GetUserReviewResponse = new GetUserReviewResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserReviewsRequest$Type extends MessageType<GetUserReviewsRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetUserReviewsRequest", [
            { no: 1, name: "userId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["wuxiaworld.api.v2.GetUserReviewsRequest.Type", GetUserReviewsRequest_Type] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetUserReviewsRequest
 */
export const GetUserReviewsRequest = new GetUserReviewsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserReviewsResponse$Type extends MessageType<GetUserReviewsResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetUserReviewsResponse", [
            { no: 1, name: "items", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ReviewItem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetUserReviewsResponse
 */
export const GetUserReviewsResponse = new GetUserReviewsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchReviewsRequest$Type extends MessageType<SearchReviewsRequest> {
    constructor() {
        super("wuxiaworld.api.v2.SearchReviewsRequest", [
            { no: 1, name: "novelId", kind: "scalar", oneof: "type", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "productId", kind: "scalar", oneof: "type", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "sortType", kind: "enum", T: () => ["wuxiaworld.api.v2.SearchReviewsRequest.SortType", SearchReviewsRequest_SortType] },
            { no: 5, name: "voteType", kind: "enum", T: () => ["wuxiaworld.api.v2.ReviewItem.VoteType", ReviewItem_VoteType] },
            { no: 4, name: "pageInfo", kind: "message", T: () => PageInfoRequest, options: { "wuxiaworld.api.v2.required": { value: true } } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.SearchReviewsRequest
 */
export const SearchReviewsRequest = new SearchReviewsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchReviewsResponse$Type extends MessageType<SearchReviewsResponse> {
    constructor() {
        super("wuxiaworld.api.v2.SearchReviewsResponse", [
            { no: 1, name: "items", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ReviewItem },
            { no: 2, name: "pageInfo", kind: "message", T: () => PageInfoResponse }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.SearchReviewsResponse
 */
export const SearchReviewsResponse = new SearchReviewsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReviewerSeriesInfo$Type extends MessageType<ReviewerSeriesInfo> {
    constructor() {
        super("wuxiaworld.api.v2.ReviewerSeriesInfo", [
            { no: 1, name: "isChampion", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.ReviewerSeriesInfo
 */
export const ReviewerSeriesInfo = new ReviewerSeriesInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReviewerEntityInfo$Type extends MessageType<ReviewerEntityInfo> {
    constructor() {
        super("wuxiaworld.api.v2.ReviewerEntityInfo", [
            { no: 1, name: "seriesInfo", kind: "message", oneof: "entityInfo", T: () => ReviewerSeriesInfo }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.ReviewerEntityInfo
 */
export const ReviewerEntityInfo = new ReviewerEntityInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReviewItem$Type extends MessageType<ReviewItem> {
    constructor() {
        super("wuxiaworld.api.v2.ReviewItem", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "content", kind: "message", T: () => StringValue },
            { no: 3, name: "reviewedAt", kind: "message", T: () => Timestamp },
            { no: 4, name: "editedAt", kind: "message", T: () => Timestamp },
            { no: 5, name: "reviewUser", kind: "message", T: () => UserItem },
            { no: 6, name: "reviewUserPast", kind: "message", T: () => ReviewItem_PastUser },
            { no: 7, name: "votes", kind: "message", T: () => ReviewItem_Votes },
            { no: 8, name: "totalComments", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "novelId", kind: "scalar", oneof: "type", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "productId", kind: "scalar", oneof: "type", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "voteType", kind: "enum", T: () => ["wuxiaworld.api.v2.ReviewItem.VoteType", ReviewItem_VoteType] },
            { no: 12, name: "hasPurchased", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 13, name: "rejectionInfo", kind: "message", T: () => ReviewItem_RejectionInfo },
            { no: 14, name: "reviewerEntityInfo", kind: "message", T: () => ReviewerEntityInfo }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.ReviewItem
 */
export const ReviewItem = new ReviewItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReviewItem_Votes$Type extends MessageType<ReviewItem_Votes> {
    constructor() {
        super("wuxiaworld.api.v2.ReviewItem.Votes", [
            { no: 1, name: "upVotes", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "downVotes", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.ReviewItem.Votes
 */
export const ReviewItem_Votes = new ReviewItem_Votes$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReviewItem_RejectionInfo$Type extends MessageType<ReviewItem_RejectionInfo> {
    constructor() {
        super("wuxiaworld.api.v2.ReviewItem.RejectionInfo", [
            { no: 1, name: "state", kind: "enum", T: () => ["wuxiaworld.api.v2.ReviewItem.RejectionInfo.State", ReviewItem_RejectionInfo_State] },
            { no: 2, name: "reason", kind: "message", T: () => StringValue },
            { no: 3, name: "rejectedAt", kind: "message", T: () => Timestamp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.ReviewItem.RejectionInfo
 */
export const ReviewItem_RejectionInfo = new ReviewItem_RejectionInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReviewItem_PastUser$Type extends MessageType<ReviewItem_PastUser> {
    constructor() {
        super("wuxiaworld.api.v2.ReviewItem.PastUser", [
            { no: 1, name: "isVip", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.ReviewItem.PastUser
 */
export const ReviewItem_PastUser = new ReviewItem_PastUser$Type();
/**
 * @generated ServiceType for protobuf service wuxiaworld.api.v2.Reviews
 */
export const Reviews = new ServiceType("wuxiaworld.api.v2.Reviews", [
    { name: "CreateReview", options: {}, I: CreateReviewRequest, O: CreateReviewResponse },
    { name: "UpdateReview", options: {}, I: UpdateReviewRequest, O: UpdateReviewResponse },
    { name: "SubmitReviewVote", options: {}, I: SubmitReviewVoteRequest, O: SubmitReviewVoteResponse },
    { name: "GetUserReview", options: {}, I: GetUserReviewRequest, O: GetUserReviewResponse },
    { name: "GetUserReviews", options: {}, I: GetUserReviewsRequest, O: GetUserReviewsResponse },
    { name: "SearchReviews", options: {}, I: SearchReviewsRequest, O: SearchReviewsResponse }
]);
