// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/sponsors.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { ProductItem } from "./products";
import { Int32Value } from "../google/protobuf/wrappers";
import { DecimalValue } from "./types";
import { StringValue } from "../google/protobuf/wrappers";
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetSponsorPlansRequest
 */
export interface GetSponsorPlansRequest {
    /**
     * @generated from protobuf field: int32 novelId = 1;
     */
    novelId: number;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.GetSponsorPlansRequest.SortType sortType = 2;
     */
    sortType: GetSponsorPlansRequest_SortType;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.GetSponsorPlansRequest.SortDirection sortDirection = 3;
     */
    sortDirection: GetSponsorPlansRequest_SortDirection;
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.GetSponsorPlansRequest.SortType
 */
export enum GetSponsorPlansRequest_SortType {
    /**
     * @generated from protobuf enum value: None = 0;
     */
    None = 0,
    /**
     * @generated from protobuf enum value: Name = 1;
     */
    Name = 1,
    /**
     * @generated from protobuf enum value: Popular = 2;
     */
    Popular = 2,
    /**
     * @generated from protobuf enum value: AdvanceChapters = 3;
     */
    AdvanceChapters = 3
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.GetSponsorPlansRequest.SortDirection
 */
export enum GetSponsorPlansRequest_SortDirection {
    /**
     * @generated from protobuf enum value: ASC = 0;
     */
    ASC = 0,
    /**
     * @generated from protobuf enum value: DESC = 1;
     */
    DESC = 1
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetSponsorPlansResponse
 */
export interface GetSponsorPlansResponse {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.SponsorPlanItem items = 1;
     */
    items: SponsorPlanItem[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.SponsorPlanItem
 */
export interface SponsorPlanItem {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: google.protobuf.StringValue description = 3;
     */
    description?: StringValue;
    /**
     * @generated from protobuf field: bool enabled = 4;
     */
    enabled: boolean;
    /**
     * @generated from protobuf field: bool visible = 5;
     */
    visible: boolean;
    /**
     * @generated from protobuf field: int32 advanceChapterCount = 6;
     */
    advanceChapterCount: number;
    /**
     * @generated from protobuf field: string planId = 7;
     */
    planId: string;
    /**
     * @generated from protobuf field: customTypes.DecimalValue price = 8;
     */
    price?: DecimalValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value karmaPrice = 9;
     */
    karmaPrice?: Int32Value;
    /**
     * @generated from protobuf field: bool paused = 10;
     */
    paused: boolean;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.SponsorPlanItem.NovelInfo novelInfo = 11;
     */
    novelInfo?: SponsorPlanItem_NovelInfo;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ProductItem product = 12;
     */
    product?: ProductItem;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.SponsorPlanItem.NovelInfo
 */
export interface SponsorPlanItem_NovelInfo {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string slug = 3;
     */
    slug: string;
    /**
     * @generated from protobuf field: google.protobuf.StringValue coverUrl = 4;
     */
    coverUrl?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue coverBlurHash = 5;
     */
    coverBlurHash?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue sponsorDescription = 6;
     */
    sponsorDescription?: StringValue;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetSponsorPlansRequest$Type extends MessageType<GetSponsorPlansRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetSponsorPlansRequest", [
            { no: 1, name: "novelId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "sortType", kind: "enum", T: () => ["wuxiaworld.api.v2.GetSponsorPlansRequest.SortType", GetSponsorPlansRequest_SortType] },
            { no: 3, name: "sortDirection", kind: "enum", T: () => ["wuxiaworld.api.v2.GetSponsorPlansRequest.SortDirection", GetSponsorPlansRequest_SortDirection] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetSponsorPlansRequest
 */
export const GetSponsorPlansRequest = new GetSponsorPlansRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSponsorPlansResponse$Type extends MessageType<GetSponsorPlansResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetSponsorPlansResponse", [
            { no: 1, name: "items", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => SponsorPlanItem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetSponsorPlansResponse
 */
export const GetSponsorPlansResponse = new GetSponsorPlansResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SponsorPlanItem$Type extends MessageType<SponsorPlanItem> {
    constructor() {
        super("wuxiaworld.api.v2.SponsorPlanItem", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "message", T: () => StringValue },
            { no: 4, name: "enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "visible", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "advanceChapterCount", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "planId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "price", kind: "message", T: () => DecimalValue },
            { no: 9, name: "karmaPrice", kind: "message", T: () => Int32Value },
            { no: 10, name: "paused", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 11, name: "novelInfo", kind: "message", T: () => SponsorPlanItem_NovelInfo },
            { no: 12, name: "product", kind: "message", T: () => ProductItem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.SponsorPlanItem
 */
export const SponsorPlanItem = new SponsorPlanItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SponsorPlanItem_NovelInfo$Type extends MessageType<SponsorPlanItem_NovelInfo> {
    constructor() {
        super("wuxiaworld.api.v2.SponsorPlanItem.NovelInfo", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "coverUrl", kind: "message", T: () => StringValue },
            { no: 5, name: "coverBlurHash", kind: "message", T: () => StringValue },
            { no: 6, name: "sponsorDescription", kind: "message", T: () => StringValue }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.SponsorPlanItem.NovelInfo
 */
export const SponsorPlanItem_NovelInfo = new SponsorPlanItem_NovelInfo$Type();
/**
 * @generated ServiceType for protobuf service wuxiaworld.api.v2.Sponsors
 */
export const Sponsors = new ServiceType("wuxiaworld.api.v2.Sponsors", [
    { name: "GetSponsorPlans", options: {}, I: GetSponsorPlansRequest, O: GetSponsorPlansResponse }
]);
