// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/types.proto" (package "customTypes", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Example: 12345.6789 -> { units = 12345, nanos = 678900000 }
 *
 * @generated from protobuf message customTypes.DecimalValue
 */
export interface DecimalValue {
    /**
     * Whole units part of the amount
     *
     * @generated from protobuf field: int64 units = 1;
     */
    units: number;
    /**
     * Nano units of the amount (10^-9)
     * Must be same sign as units
     *
     * @generated from protobuf field: sfixed32 nanos = 2;
     */
    nanos: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class DecimalValue$Type extends MessageType<DecimalValue> {
    constructor() {
        super("customTypes.DecimalValue", [
            { no: 1, name: "units", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 2, name: "nanos", kind: "scalar", T: 15 /*ScalarType.SFIXED32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message customTypes.DecimalValue
 */
export const DecimalValue = new DecimalValue$Type();
